# -*- coding: utf-8 -*-
"""Miniproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ATMZ6FCLAW5YlPF8iu4FZWPRzdCjOBV
"""

import requests
import time
import json
from datetime import datetime

# Header
headers = {"User-Agent": "TrendPulse/1.0"}

# API URLs
TOP_URL = "https://hacker-news.firebaseio.com/v0/topstories.json"
ITEM_URL = "https://hacker-news.firebaseio.com/v0/item/{}.json"

# Categories with keywords
categories = {
    "technology": ["ai","software","tech","code","computer","data","cloud","api","gpu","llm"],
    "worldnews": ["war","government","country","president","election","climate","attack","global"],
    "sports": ["nfl","nba","fifa","sport","game","team","player","league","championship"],
    "science": ["research","study","space","physics","biology","discovery","nasa","genome"],
    "entertainment": ["movie","film","music","netflix","game","book","show","award","streaming"]
}

# Function to detect category
def get_category(title):
    title = title.lower()
    for cat, keys in categories.items():
        for k in keys:
            if k in title:
                return cat
    return None

# Storage
collected = []
count = {c: 0 for c in categories}

# Fetch top story IDs (reduced for speed)
try:
    ids = requests.get(TOP_URL, headers=headers).json()[:300]
except:
    ids = []

# Loop category-wise
for cat in categories:
    print(f"Processing category: {cat}")

    for i in ids:
        if count[cat] >= 25:
            break

        try:
            res = requests.get(ITEM_URL.format(i), headers=headers).json()

            if not res or "title" not in res:
                continue

            if get_category(res["title"]) == cat:
                data = {
                    "post_id": res.get("id"),
                    "title": res.get("title"),
                    "category": cat,
                    "score": res.get("score", 0),
                    "num_comments": res.get("descendants", 0),
                    "author": res.get("by", "unknown"),
                    "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                }

                collected.append(data)
                count[cat] += 1

        except:
            print("Error fetching:", i)

    # Required sleep (as per instructions)
    time.sleep(2)

# Save JSON (Colab-friendly)
file = f"trends_{datetime.now().strftime('%Y%m%d')}.json"

with open(file, "w") as f:
    json.dump(collected, f, indent=4)

print(f"\nCollected {len(collected)} stories.")
print(f"Saved to {file}")

from google.colab import files
files.download(file)

"""task2

"""

import json
import csv
from google.colab import files

# Upload file
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# Load data
with open(filename, "r", encoding="utf-8") as f:
    data = json.load(f)

cleaned_data = []

for item in data:
    if "title" not in item or not item["title"]:
        continue

    cleaned_data.append({
        "post_id": item.get("post_id"),
        "title": item.get("title", "").strip(),
        "category": item.get("category"),
        "score": item.get("score", 0),
        "num_comments": item.get("num_comments", 0),
        "author": item.get("author", "").strip(),
        "collected_at": item.get("collected_at")
    })

# Save CSV safely
csv_file = "cleaned_trends.csv"

if len(cleaned_data) > 0:
    with open(csv_file, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=cleaned_data[0].keys())
        writer.writeheader()
        writer.writerows(cleaned_data)

    print("Saved:", csv_file)
    print("Total records:", len(cleaned_data))

    files.download(csv_file)
else:
    print("No valid data found!")

"""TASK3

"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

# Get uploaded filename
filename = list(uploaded.keys())[0]

# Load CSV
df = pd.read_csv(filename)

# 1. Total stories
print("Total Stories:", len(df))

# 2. Stories per category
print("\nStories per Category:")
print(df["category"].value_counts())

# 3. Top 5 stories by score
print("\nTop 5 Stories by Score:")
top5 = df.sort_values(by="score", ascending=False)[["title", "score"]].head()
print(top5)

# 4. Average comments
print("\nAverage Comments:", df["num_comments"].mean())